version: '3.7'
services:
  student_database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: studentdb
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pg_data:
